# projet_blockchain_python

Nous avons une erreur liée au module pybind11 (erreur insolvable), nous n'avons donc pas pu tester.

Le screen de l'erreur est uploadée dans le repository
