# projet_blockchain_python

Nous avons une erreur li√©e au module pybind11 (erreur insolvable), nous n'avons donc pas pu tester.

![Error](https://prnt.sc/1all5ti)
